### ISSUE TITLE
Need help with API 

### ISSUE THREAD

**Issue by ViktorPavlovA** [cj-mills/byte-track-eigen#4]
Hello, can you show how get id of tracked bbox?

**Comment by ViktorPavlovA** [comment]
My test code looks like this:

```
#include <iostream>
#include <vector>
#include <memory>
#include <Eigen/Dense>
#include "BYTETracker.h" 

int main() {
  BYTETracker tracker;

  Eigen::MatrixXf detections(3, 5); 
  detections << 10, 10, 20, 20, 0.9, 
                30, 30, 40, 40, 0.8, 
                50, 50, 60, 60, 0.7; 
  std::vector<KalmanBBoxTrack> tracked_objects = tracker.process_frame_detections(detections);



  for (size_t i = 0; i < tracked_objects.size(); i++){
    auto tlwh = tracked_objects[i].tlwh();
    auto track_id = tracked_objects[i].track_id;
    std::cout << "tlwh:" << tlwh<< std::endl;
    std::cout << "Track_id:" << track_id << std::endl;

}

  return 0;
}
```

**Comment by cj-mills** [comment]
Hi @ViktorPavlovA,

You need to use the [`match_detections_with_tracks`](https://github.com/cj-mills/byte-track-eigen/blob/a865158906f6138465668810a98ffd918d95f9a3/src/BoundingBoxIoUMatching.cpp#L95) function after passing the latest detection info to the `tracker.process_frame_detections` method.

You can check out the relevant code from the two demo projects to see how to use it:

* **yolox-bytetrack-onnx-demo:** [YOLOXByteTrackONNXDemo/YOLOXByteTrackONNXDemo.cpp](https://github.com/cj-mills/yolox-bytetrack-onnx-demo/blob/b5f0a82903b6dbd4906ded3867f600598b82397e/YOLOXByteTrackONNXDemo/YOLOXByteTrackONNXDemo.cpp#L175)
* **unity-bytetrack-plugin:** [UnityByteTrackPlugin/dllmain.cpp](https://github.com/cj-mills/unity-bytetrack-plugin/blob/7917216db3ee05ea88e8932fb3add9e122674f31/UnityByteTrackPlugin/dllmain.cpp#L34)

**Comment by ViktorPavlovA** [comment]
Thanks, i will try 🙂

**Comment by ViktorPavlovA** [comment]
@cj-mills, thank you! i get track id of object but another question is how to  predict boxes which lost between frames ? For example in 1st frame i found box collect id of box, on 2nd frame i miss box who to predict bbox location?

**Comment by cj-mills** [comment]
@ViktorPavlovA,
As long as the object detection model detects the target object again in a later frame and the object has not moved too much or suddenly changed directions since it was last detected, the tracker should determine that it is the same object based on its internal track for that object.

I recommend walking through the code for the demos linked above. You can also walk through the code for the object tracker starting from the `process_frame_detections` method linked below:

- **src/BYTETracker.cpp:** [`process_frame_detections`](https://github.com/cj-mills/byte-track-eigen/blob/main/src/BYTETracker.cpp#L372)

**Comment by ViktorPavlovA** [comment]
Thank you
